CREATE TABLE IF NOT EXISTS `s155_items` (
  `id` int(10) unsigned NOT NULL auto_increment,
  `title` varchar(255) default '',
  `description` text NOT NULL,
  `when` int(11) NOT NULL default '0',
  `rate` float NOT NULL,
  `rate_count` int(11) unsigned NOT NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO `s155_items` (`title`, `description`, `when`, `rate`, `rate_count`) VALUES 
('CHE 102', 'Chemistry for Engineers', UNIX_TIMESTAMP(), '0', '0'),
('ECE 103', 'Discrete Mathematics', UNIX_TIMESTAMP()+2, '0', '0'),
('ECE 105', 'Physics of Electrical Engineering 1', UNIX_TIMESTAMP()+3, '0', '0'),
('ECE 106', 'Physics of Electrical Engineering 2', UNIX_TIMESTAMP()+4, '0', '0'), 
('ECE 124', 'Digital Circuits and Systems', UNIX_TIMESTAMP()+5, '0', '0'),
('ECE 140', 'Linear Circuits', UNIX_TIMESTAMP()+6, '0', '0'),
('ECE 150', 'Fundamentals of Programming', UNIX_TIMESTAMP()+8, '0', '0'),
('ECE 155', 'Engineering Design with Embedded Systems', UNIX_TIMESTAMP()+7, '0', '0'),
('MATH 117', 'Calculus 1 for Engineering', UNIX_TIMESTAMP()+8, '0', '0'),
('MATH 119', 'Calculus 2 for Engineering', UNIX_TIMESTAMP()+9, '0', '0'),

('ECE 204A', 'Numerical Methods 1', UNIX_TIMESTAMP()+10, '0', '0'),
('ECE 204B', 'Numerical Methods 2', UNIX_TIMESTAMP()+11, '0', '0'),
('ECE 205', 'Advanced Calculus 1', UNIX_TIMESTAMP()+12, '0', '0'),
('ECE 206', 'Advanced Calculus 2', UNIX_TIMESTAMP()+13, '0', '0'),
('ECE 207', 'Signals and Systems', UNIX_TIMESTAMP()+14, '0', '0'),
('ECE 209', 'Electronic and Electrical Properties of Materials', UNIX_TIMESTAMP()+15, '0', '0'),
('ECE 222', 'Digital Computers', UNIX_TIMESTAMP()+16, '0', '0'),
('ECE 224', 'Embedded Microprocessor Systems', UNIX_TIMESTAMP()+17, '0', '0'),
('ECE 240', 'Electronic Circuits 1', UNIX_TIMESTAMP()+18, '0', '0'),
('ECE 242', 'Electronic Circuits 2', UNIX_TIMESTAMP()+19, '0', '0'),
('ECE 250', 'Algorithms and Data Structures', UNIX_TIMESTAMP()+20, '0', '0'),
('ECE 254', 'Operating Systems and Systems Programming', UNIX_TIMESTAMP()+21, '0', '0'),
('ECE 290', 'Engineering Profession, Ethics, and Law', UNIX_TIMESTAMP()+22, '0', '0'),
('MATH 215', 'Linear Algebra', UNIX_TIMESTAMP()+23, '0', '0'),


('ECE 309', 'Introduction to Thermodynamics and Heat Transfer', UNIX_TIMESTAMP()+24, '0', '0'),
('ECE 316 ', 'Probability Theory and Statistics', UNIX_TIMESTAMP()+25, '0', '0'),
('ECE 318', 'Analog and Digital Communications', UNIX_TIMESTAMP()+26, '0', '0'),
('ECE 327', 'Digital Hardware Systems', UNIX_TIMESTAMP()+27, '0', '0'),
('ECE 331', 'Electronic Devices', UNIX_TIMESTAMP()+28, '0', '0'),
('ECE 351', 'Compilers', UNIX_TIMESTAMP()+29, '0', '0'),
('ECE 356', 'Database Systems', UNIX_TIMESTAMP()+30, '0', '0'),
('ECE 358', 'Computer Networks', UNIX_TIMESTAMP()+31, '0', '0'),
('ECE 361', 'Power Systems and Components', UNIX_TIMESTAMP()+32, '0', '0'),
('ECE 375', 'Electromagnetic Fields and Waves', UNIX_TIMESTAMP()+32, '0', '0'),
('ECE 380', 'Analog Control Systems', UNIX_TIMESTAMP()+34, '0', '0'),
('ECE 390', 'Engineering Design, Economics, and Impact on Society', UNIX_TIMESTAMP()+35, '0', '0'),

('ECE 403', 'Thermal Physics', UNIX_TIMESTAMP()+36, '0', '0'),
('ECE 404 ', 'Geometrical and Physical Optics', UNIX_TIMESTAMP()+37, '0', '0'),
('ECE 405', 'Introduction to Quantum Mechanics', UNIX_TIMESTAMP()+38, '0', '0'),
('ECE 406', 'Algorithm Design and Analysis', UNIX_TIMESTAMP()+39, '0', '0'),
('ECE 409', 'Cryptography and System Security', UNIX_TIMESTAMP()+40, '0', '0'),
('ECE 413', 'Digital Signal and Image Processing', UNIX_TIMESTAMP()+41, '0', '0'),
('ECE 414', 'Wireless Communications', UNIX_TIMESTAMP()+42, '0', '0'),
('ECE 415', 'Multimedia Processing and Coding', UNIX_TIMESTAMP()+43, '0', '0'),
('ECE 416', 'Higher Level Network Protocols', UNIX_TIMESTAMP()+44, '0', '0'),
('ECE 418', 'Communications Networks', UNIX_TIMESTAMP()+45, '0', '0'),
('ECE 420', 'Electrical Applications on Herbal Systems', UNIX_TIMESTAMP()+46, '0', '0'),
('ECE 423', 'Embedded Computer Systems', UNIX_TIMESTAMP()+47, '0', '0'),
('ECE 429', 'Computer Architecture', UNIX_TIMESTAMP()+48, '0', '0'),
('ECE 432', 'Radio Frequency Integrated Devices and Circuits', UNIX_TIMESTAMP()+49, '0', '0'),
('ECE 433', 'Fabrication Technologies for Micro and Nano Devices', UNIX_TIMESTAMP()+50, '0', '0'),
('ECE 444', 'Integrated Analog Electronics', UNIX_TIMESTAMP()+51, '0', '0'),
('ECE 445', 'Integrated Digital Electronics', UNIX_TIMESTAMP()+52, '0', '0'),
('ECE 451', 'Software Requirements Specification and Analysis', UNIX_TIMESTAMP()+53, '0', '0'),
('ECE 452', 'Software Design and Architectures', UNIX_TIMESTAMP()+54, '0', '0'),
('ECE 453', 'Software Testing, Quality Assurance and Maintenance', UNIX_TIMESTAMP()+55, '0', '0'),
('ECE 454', 'Distributed Computing', UNIX_TIMESTAMP()+56, '0', '0'),
('ECE 455', 'Embedded Software', UNIX_TIMESTAMP()+57, '0', '0'),
('ECE 457A', 'Cooperative and Adaptive Algorithms', UNIX_TIMESTAMP()+58, '0', '0'),
('ECE 457B', 'Fundamentals of Computational Intelligence', UNIX_TIMESTAMP()+59, '0', '0'),
('ECE 458', 'Computer Security', UNIX_TIMESTAMP()+60, '0', '0'),
('ECE 459', 'Programming for Performance', UNIX_TIMESTAMP()+61, '0', '0'),
('ECE 462', 'Electrical Distribution Systems', UNIX_TIMESTAMP()+62, '0', '0'),
('ECE 463', 'Design & Applications of Power Electronic Converters', UNIX_TIMESTAMP()+63, '0', '0'),
('ECE 464', 'High Voltage Engineering and Power System Protection', UNIX_TIMESTAMP()+64, '0', '0'),
('ECE 467', 'Power System Operation and Markets', UNIX_TIMESTAMP()+65, '0', '0'),
('ECE 473', 'Radio Frequency and Microwave Circuits', UNIX_TIMESTAMP()+66, '0', '0'),
('ECE 474', 'Radio and Wireless Systems', UNIX_TIMESTAMP()+67, '0', '0'),
('ECE 475', 'Radio-Wave Systems', UNIX_TIMESTAMP()+68, '0', '0'),
('ECE 477', 'Photonic Devices and Systems', UNIX_TIMESTAMP()+69, '0', '0'),
('ECE 481', 'Digital Control Systems', UNIX_TIMESTAMP()+70, '0', '0'),
('ECE 484 ', 'Digital Control Applications', UNIX_TIMESTAMP()+71, '0', '0'),
('ECE 486', 'Robot Dynamics and Control', UNIX_TIMESTAMP()+72, '0', '0'),
('ECE 488', 'Multivariable Control Systems', UNIX_TIMESTAMP()+73, '0', '0'),
('ECE 493', 'Special Topics in Electrical and Computer Engineering', UNIX_TIMESTAMP()+74, '0', '0'),
('ECE 498A', 'Engineering Design Project', UNIX_TIMESTAMP()+75, '0', '0'),
('ECE 498B', 'Engineering Design Project', UNIX_TIMESTAMP()+76, '0', '0'),
('ECE 499', 'Engineering Project', UNIX_TIMESTAMP()+77, '0', '0');

CREATE TABLE `s155_items_vote_track` (
  `item_id` int(11) unsigned NOT NULL default '0',
  `ip` varchar(20) default NULL,
  `date` datetime default NULL,
  KEY `med_ip` (`ip`,`item_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;